framework:
    messenger:
        failure_transport: failed
        transports:
             async:
               dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
               retry_strategy:
                 max_retries: 3
                 delay: 600000 #10 minutes
                 multiplier: 3
                 max_delay: 0

             failed: '%env(MESSENGER_FAILED_TRANSPORT_DSN)%'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
             App\Message\ImportOperationMessage: async
