monolog:
    handlers:
        main:
            type: stream
            path: php://stderr
            level: warning
            channels: ["!event"]
        file:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.debug.log"
            level: debug
            channels: [ "!event" ]
        normal:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: warning
            channels: [ "!event" ]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
