parameters:
    import_path: '%kernel.project_dir%/data/import/operation'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $privateStoragePath: '%kernel.project_dir%/data/'
            $importStoragePath: '%import_path%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\MessageHandler\ImportOperationMessageHandler:
        arguments:
            $handlers:
                - '@App\MessageHandler\Chain\Import\Steps\LocationHandler'
                - '@App\MessageHandler\Chain\Import\Steps\TypeHandler'
                - '@App\MessageHandler\Chain\Import\Steps\DateHandler'
                - '@App\MessageHandler\Chain\Import\Steps\MoneyHandler'
                - '@App\MessageHandler\Chain\Import\Steps\OtherHandler'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    datetime_normalizer:
        class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
        tags:
            - { name: serializer.normalizer }
