version: '3'

services:
  db:
    image: 'mysql:8'
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_USER=main
      - MYSQL_PASSWORD=main
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - '3306:3306'
    volumes:
      - ./var/mysql:/var/lib/mysql
